### ISSUE TITLE
Row index required in onCellTap

### ISSUE THREAD

**Issue by NatashaFatima** [ZainUlMustafa/Fluttable#6]
I'm using fluttable to show a table displaying some of the properties of objects that I'm getting in a list. I've made one whole column tappable and I want to pass the object of that specific row index to another page when a cell is tapped. Can I get the row index in onCellTap to make this possible?

**Comment by ZainUlMustafa** [comment]
Good suggestion. I'll make it available

**Comment by ZainUlMustafa** [comment]
Fixed this issue in https://github.com/ZainUlMustafa/Fluttable/tree/tap-able-cells

Will be released as a main feature in v1.2.3

**Comment by NatashaFatima** [comment]
Right thanks!
